name: test
on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . -t rsc-vm

    - name: Run the Tests
      run: |
        cargo test